ThunderCats.Web/Controllers/ActorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ThunderCats.Database;
using ThunderCats.Entities;
using ThunderCats.Services;
using ThunderCats.Services.GenericServices;

namespace ThunderCats.Web.Controllers
{
    public class ActorController : Controller
    {
       private IGenericRepository<Actor> Repository { get; set; }

        public ActorController()
        {
            Repository = new GenericRepository<Actor>();
        }

        public ActorController(IGenericRepository<Actor> repository)
        {
            Repository = repository;
        }

        // GET: Actor
        public ActionResult Index(string searchActor)
        {

            var model = Repository.GetAll();
            return View(model);
        }



        // GET: Actor/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
             Actor model = Repository.GetById(id);
           
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }


        // GET: Actor/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Actor/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Age")] Actor actor)
        {
            if (ModelState.IsValid)
            {
                Repository.Insert(actor);
                Repository.Save();
                
                return RedirectToAction("Index");
            }

            return View(actor);
        }

        // GET: Actor/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Actor model = Repository.GetById(id);

            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // POST: Actor/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Age")] Actor actor)
        {
            if (ModelState.IsValid)
            {
                Repository.Update(actor);
                return RedirectToAction("Index");
            }
            return View(actor);
        }

        // GET: Actor/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           Actor model = Repository.GetById(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // POST: Actor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Repository.Delete(id);
            Repository.Save();
            return RedirectToAction("Index");
        }

    }
}

ThunderCats.Web/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ThunderCats.Database;
using ThunderCats.Entities;
using ThunderCats.Entities.ViewModels;

namespace ThunderCats.Web.Controllers
{
    public class MovieController : Controller
    {
        private TsirkoContext db = new TsirkoContext();

        // GET: Movie
        public ActionResult Index()
        {
            var movies = db.Movies.Include(m => m.Category).Include(m => m.Director).Include(a => a.Actors);
            return View(movies.ToList());
        }


        // GET: Movie/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }



        // GET: Movie/Create
        public ActionResult Create()
        {
            ViewBag.Genre = new SelectList(db.Categories, "Name", "Name");
            ViewBag.DirectorId = new SelectList(db.Directors, "Id", "Name");


            MovieViewModel vm = new MovieViewModel()
            {
                Movie = new Movie(),
                Actors = db.Actors.Select(x => new SelectListItem()
                {
                    Value = x.Id.ToString(),
                    Text = x.Name                  
                })
            };

            return View(vm);
        }


        // POST: Movie/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MovieViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Genre = new SelectList(db.Categories, "Name", "Name", vm.Movie.Genre);
                ViewBag.DirectorId = new SelectList(db.Directors, "Id", "Name", vm.Movie.DirectorId);
                return View(vm);
                //ViewBag.ActorId = new SelectList(db.Actors, "Id", "Name", vm.Movie.ActorId);

            }
            foreach (int id in vm.SelectedActors)
            {
                Actor actor = db.Actors.Find(id);
                if (actor != null)
                {
                    vm.Movie.Actors.Add(actor);
                }
            }

            db.Movies.Add(vm.Movie);
            db.SaveChanges();

            return RedirectToAction("Index");

            //Leipei kodikas paromoios me ton apo pano tis Get Create gia na provalw tous actors se periptosi pou den petixei to validation
        }


        // GET: Movie/Edit/5
        public ActionResult Edit(int? id)
        {

            Movie movie = db.Movies.Include("Category").Include("Director").Include("Actors")
                                   .Where(x => x.Id == id).FirstOrDefault();


            if (movie == null)
            {
                return HttpNotFound();
            }
            ViewBag.Genre = new SelectList(db.Categories, "Name", "Name", movie.Genre);
            ViewBag.DirectorId = new SelectList(db.Directors, "Id", "Name", movie.DirectorId);

            MovieViewModel vm = new MovieViewModel()
            {
                Movie = movie,
                Actors = db.Actors.Select(x => new SelectListItem()
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                })
            };


            return View(vm);
        }


        // POST: Movie/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MovieViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Genre = new SelectList(db.Categories, "Name", "Name", vm.Movie.Genre);
                ViewBag.DirectorId = new SelectList(db.Directors, "Id", "Name", vm.Movie.DirectorId);
                return View(vm);
                //ViewBag.ActorId = new SelectList(db.Actors, "Id", "Name", vm.Movie.ActorId)
            }
            db.Movies.Attach(vm.Movie);
            db.Entry(vm.Movie).Collection("Actors").Load();
            vm.Movie.Actors.Clear();
            db.SaveChanges();
            foreach (int id in vm.SelectedActors)
            {
                Actor actor = db.Actors.Find(id);
                if (actor != null)
                {
                    vm.Movie.Actors.Add(actor);
                }
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        // GET: Movie/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }


        // POST: Movie/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Movie movie = db.Movies.Find(id);
            db.Movies.Remove(movie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ThunderCats.Web/Views/Shared/_Footer.cshtml
@*<footer class="page-footer footer special-color-dark pt-4" style="bottom:0;position: fixed; width:100%;">*@

    <div >
        Number of Users Online:  <strong id="counter">  </strong>

        @section scripts{

            <script src="~/Scripts/jquery-3.3.1.min.js"></script>
            <script src="~/Scripts/jquery.signalR-2.2.2.min.js"></script>
            <!--Reference the autogenerated SignalR hub script. -->
            <script src="~/signalr/hubs"></script>

            <script type="text/javascript">
               
                $(function () {

                    var myHub = $.connection.counterHub;

                    $.connection.hub.start().done(function () {


                         myHub.client.UpdateCount = function (count) {
                        $("#counter").text(count);
                    }





                    });

                   



                });
            </script>
        }
    </div>

    @*</footer>*@

ThunderCats.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MoviesApp</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    

    <script type="text/javascript">
        function toggleSidebar() {
            document.getElementById("sidebar").classList.toggle('active');
        }
    </script>

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    <img src="~/Images/cinema.jpg" id="bg" alt="">
    @Html.Partial("_NavbarVertical")

    <div class="container body-content">
        @RenderBody()


    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/signalr")
    @Scripts.Render("~/signalr/hubs")

    @RenderSection("scripts", required: false)

</body>
</html>

ThunderCats.Web/Views/Shared/_NavbarVertical.cshtml
@using Microsoft.AspNet.Identity

@if (Request.IsAuthenticated)
{
    <div id="sidebar">

        <div class="toggle-btn" onclick="toggleSidebar()">
            <a>
                <span></span>

                <span></span>

                <span></span>
            </a>

        </div>
      
        <ul>
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("About", "About", "Home")</li>
            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            <li>@Html.ActionLink("Actors", "Index", "Actor")</li>
            <li>@Html.ActionLink("Directors", "Index", "Director")</li>
            <li>@Html.ActionLink("Movies", "Index", "Movie")</li>
            <li>@Html.ActionLink("Categories", "Index", "Category")</li>

            <br />
            <li>@Html.ActionLink("Chat", "Chat", "Home")</li>
        </ul>

        @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
        {
            @Html.AntiForgeryToken()
            <ul>
                <li>
                    @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                </li>
                <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
            </ul>
        }
    </div>
}
else
{
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div>
                    @Html.ActionLink("Cool Movies", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.Partial("_LoginPartial")

                    @Html.ActionLink("Paypal", "PaymentWithPaypal", "Home", null, new { @class = "navbar-brand" })
                </div>
            </div>
    
               
                @*<div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">

                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Movies", "Index", "Movie")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>*@
                @*<ul class="add-button">
            <li class="sub-button tl">@Html.ActionLink("H", "Index", "Home")</li>
            <li class="sub-button tr"> @Html.ActionLink("M", "Index", "Movie")</li>
            <li class="sub-button bl"> @Html.ActionLink("A", "About", "Home")</li>
            <li class="sub-button br"> @Html.ActionLink("C", "Contact", "Home")</li>
        </ul>*@

                <div class="add-button">
                    @Html.ActionLink("H", "Index", "Home", null, new { @class = "sub-button tl" })
                    @Html.ActionLink("M", "Index", "Movie", null, new { @class = "sub-button tr" })
                    @Html.ActionLink("A", "About", "Home", null, new { @class = "sub-button bl" }))
                    @Html.ActionLink("C", "Contact", "Home", null, new { @class = "sub-button br" })

                </div>


            </div>
    </div>



}